/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyNeoHairLotionInWholesaleRouteImport } from './routes/buy-neo-hair-lotion-in-wholesale'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HairScienceRouteImport } from './routes/hair-science'
import { Route as HowToSpotFakeVsOriginalNeoHairLotionRouteImport } from './routes/how-to-spot-fake-vs-original-neo-hair-lotion'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as HowToUseNeoHairLotionRouteImport } from './routes/how-to-use-neo-hair-lotion'
import { Route as HowToVerifyOriginalNeoHairLotionRouteImport } from './routes/how-to-verify-original-neo-hair-lotion'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NeoHairLotionReviewsRouteImport } from './routes/neo-hair-lotion-reviews'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RealVsFakeRouteImport } from './routes/real-vs-fake'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as BlogsSeriesRouteImport } from './routes/blogs.series'
import { Route as ComboCodeRouteImport } from './routes/combo.$code'
import { Route as ComparisonNeoVsMinoxidilRouteImport } from './routes/comparison.neo-vs-minoxidil'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients.index'
import { Route as IngredientsSlugRouteImport } from './routes/ingredients.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PaymentCallbackIntentRouteImport } from './routes/payment.callback.$intent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyNeoHairLotionInWholesaleRoute =
  BuyNeoHairLotionInWholesaleRouteImport.update({
    id: '/buy-neo-hair-lotion-in-wholesale',
    path: '/buy-neo-hair-lotion-in-wholesale',
    getParentRoute: () => rootRouteImport,
  } as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HairScienceRoute = HairScienceRouteImport.update({
  id: '/hair-science',
  path: '/hair-science',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToSpotFakeVsOriginalNeoHairLotionRoute =
  HowToSpotFakeVsOriginalNeoHairLotionRouteImport.update({
    id: '/how-to-spot-fake-vs-original-neo-hair-lotion',
    path: '/how-to-spot-fake-vs-original-neo-hair-lotion',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseNeoHairLotionRoute = HowToUseNeoHairLotionRouteImport.update({
  id: '/how-to-use-neo-hair-lotion',
  path: '/how-to-use-neo-hair-lotion',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToVerifyOriginalNeoHairLotionRoute =
  HowToVerifyOriginalNeoHairLotionRouteImport.update({
    id: '/how-to-verify-original-neo-hair-lotion',
    path: '/how-to-verify-original-neo-hair-lotion',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NeoHairLotionReviewsRoute = NeoHairLotionReviewsRouteImport.update({
  id: '/neo-hair-lotion-reviews',
  path: '/neo-hair-lotion-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RealVsFakeRoute = RealVsFakeRouteImport.update({
  id: '/real-vs-fake',
  path: '/real-vs-fake',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSeriesRoute = BlogsSeriesRouteImport.update({
  id: '/blogs/series',
  path: '/blogs/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboCodeRoute = ComboCodeRouteImport.update({
  id: '/combo/$code',
  path: '/combo/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonNeoVsMinoxidilRoute =
  ComparisonNeoVsMinoxidilRouteImport.update({
    id: '/comparison/neo-vs-minoxidil',
    path: '/comparison/neo-vs-minoxidil',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsSlugRoute = IngredientsSlugRouteImport.update({
  id: '/ingredients/$slug',
  path: '/ingredients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackIntentRoute = PaymentCallbackIntentRouteImport.update({
  id: '/payment/callback/$intent',
  path: '/payment/callback/$intent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/buy-neo-hair-lotion-in-wholesale': typeof BuyNeoHairLotionInWholesaleRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/hair-science': typeof HairScienceRoute
  '/how-to-spot-fake-vs-original-neo-hair-lotion': typeof HowToSpotFakeVsOriginalNeoHairLotionRoute
  '/how-to-use': typeof HowToUseRoute
  '/how-to-use-neo-hair-lotion': typeof HowToUseNeoHairLotionRoute
  '/how-to-verify-original-neo-hair-lotion': typeof HowToVerifyOriginalNeoHairLotionRoute
  '/legal': typeof LegalRoute
  '/neo-hair-lotion-reviews': typeof NeoHairLotionReviewsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy': typeof PrivacyRoute
  '/real-vs-fake': typeof RealVsFakeRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-order': typeof TrackOrderRoute
  '/verify': typeof VerifyRoute
  '/wholesale': typeof WholesaleRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/series': typeof BlogsSeriesRoute
  '/combo/$code': typeof ComboCodeRoute
  '/comparison/neo-vs-minoxidil': typeof ComparisonNeoVsMinoxidilRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/ingredients/$slug': typeof IngredientsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/payment/callback/$intent': typeof PaymentCallbackIntentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/buy-neo-hair-lotion-in-wholesale': typeof BuyNeoHairLotionInWholesaleRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/hair-science': typeof HairScienceRoute
  '/how-to-spot-fake-vs-original-neo-hair-lotion': typeof HowToSpotFakeVsOriginalNeoHairLotionRoute
  '/how-to-use': typeof HowToUseRoute
  '/how-to-use-neo-hair-lotion': typeof HowToUseNeoHairLotionRoute
  '/how-to-verify-original-neo-hair-lotion': typeof HowToVerifyOriginalNeoHairLotionRoute
  '/legal': typeof LegalRoute
  '/neo-hair-lotion-reviews': typeof NeoHairLotionReviewsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy': typeof PrivacyRoute
  '/real-vs-fake': typeof RealVsFakeRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-order': typeof TrackOrderRoute
  '/verify': typeof VerifyRoute
  '/wholesale': typeof WholesaleRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/series': typeof BlogsSeriesRoute
  '/combo/$code': typeof ComboCodeRoute
  '/comparison/neo-vs-minoxidil': typeof ComparisonNeoVsMinoxidilRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/ingredients/$slug': typeof IngredientsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/payment/callback/$intent': typeof PaymentCallbackIntentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/buy-neo-hair-lotion-in-wholesale': typeof BuyNeoHairLotionInWholesaleRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/hair-science': typeof HairScienceRoute
  '/how-to-spot-fake-vs-original-neo-hair-lotion': typeof HowToSpotFakeVsOriginalNeoHairLotionRoute
  '/how-to-use': typeof HowToUseRoute
  '/how-to-use-neo-hair-lotion': typeof HowToUseNeoHairLotionRoute
  '/how-to-verify-original-neo-hair-lotion': typeof HowToVerifyOriginalNeoHairLotionRoute
  '/legal': typeof LegalRoute
  '/neo-hair-lotion-reviews': typeof NeoHairLotionReviewsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy': typeof PrivacyRoute
  '/real-vs-fake': typeof RealVsFakeRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/track-order': typeof TrackOrderRoute
  '/verify': typeof VerifyRoute
  '/wholesale': typeof WholesaleRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/series': typeof BlogsSeriesRoute
  '/combo/$code': typeof ComboCodeRoute
  '/comparison/neo-vs-minoxidil': typeof ComparisonNeoVsMinoxidilRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/ingredients/$slug': typeof IngredientsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/payment/callback/$intent': typeof PaymentCallbackIntentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/buy-neo-hair-lotion-in-wholesale'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/hair-science'
    | '/how-to-spot-fake-vs-original-neo-hair-lotion'
    | '/how-to-use'
    | '/how-to-use-neo-hair-lotion'
    | '/how-to-verify-original-neo-hair-lotion'
    | '/legal'
    | '/neo-hair-lotion-reviews'
    | '/order-confirmation'
    | '/privacy'
    | '/real-vs-fake'
    | '/refund-policy'
    | '/reset-password'
    | '/reviews'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/track-order'
    | '/verify'
    | '/wholesale'
    | '/admin/orders'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/blogs/series'
    | '/combo/$code'
    | '/comparison/neo-vs-minoxidil'
    | '/countries/$slug'
    | '/ingredients/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blogs/'
    | '/ingredients/'
    | '/payment/callback/$intent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/buy-neo-hair-lotion-in-wholesale'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/hair-science'
    | '/how-to-spot-fake-vs-original-neo-hair-lotion'
    | '/how-to-use'
    | '/how-to-use-neo-hair-lotion'
    | '/how-to-verify-original-neo-hair-lotion'
    | '/legal'
    | '/neo-hair-lotion-reviews'
    | '/order-confirmation'
    | '/privacy'
    | '/real-vs-fake'
    | '/refund-policy'
    | '/reset-password'
    | '/reviews'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/track-order'
    | '/verify'
    | '/wholesale'
    | '/admin/orders'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/blogs/series'
    | '/combo/$code'
    | '/comparison/neo-vs-minoxidil'
    | '/countries/$slug'
    | '/ingredients/$slug'
    | '/product/$slug'
    | '/admin'
    | '/blogs'
    | '/ingredients'
    | '/payment/callback/$intent'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/buy-neo-hair-lotion-in-wholesale'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/hair-science'
    | '/how-to-spot-fake-vs-original-neo-hair-lotion'
    | '/how-to-use'
    | '/how-to-use-neo-hair-lotion'
    | '/how-to-verify-original-neo-hair-lotion'
    | '/legal'
    | '/neo-hair-lotion-reviews'
    | '/order-confirmation'
    | '/privacy'
    | '/real-vs-fake'
    | '/refund-policy'
    | '/reset-password'
    | '/reviews'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/track-order'
    | '/verify'
    | '/wholesale'
    | '/admin/orders'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/blogs/series'
    | '/combo/$code'
    | '/comparison/neo-vs-minoxidil'
    | '/countries/$slug'
    | '/ingredients/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blogs/'
    | '/ingredients/'
    | '/payment/callback/$intent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuyNeoHairLotionInWholesaleRoute: typeof BuyNeoHairLotionInWholesaleRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FaqRoute: typeof FaqRoute
  HairScienceRoute: typeof HairScienceRoute
  HowToSpotFakeVsOriginalNeoHairLotionRoute: typeof HowToSpotFakeVsOriginalNeoHairLotionRoute
  HowToUseRoute: typeof HowToUseRoute
  HowToUseNeoHairLotionRoute: typeof HowToUseNeoHairLotionRoute
  HowToVerifyOriginalNeoHairLotionRoute: typeof HowToVerifyOriginalNeoHairLotionRoute
  LegalRoute: typeof LegalRoute
  NeoHairLotionReviewsRoute: typeof NeoHairLotionReviewsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PrivacyRoute: typeof PrivacyRoute
  RealVsFakeRoute: typeof RealVsFakeRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  VerifyRoute: typeof VerifyRoute
  WholesaleRoute: typeof WholesaleRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsSeriesRoute: typeof BlogsSeriesRoute
  ComboCodeRoute: typeof ComboCodeRoute
  ComparisonNeoVsMinoxidilRoute: typeof ComparisonNeoVsMinoxidilRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  IngredientsSlugRoute: typeof IngredientsSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  PaymentCallbackIntentRoute: typeof PaymentCallbackIntentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-neo-hair-lotion-in-wholesale': {
      id: '/buy-neo-hair-lotion-in-wholesale'
      path: '/buy-neo-hair-lotion-in-wholesale'
      fullPath: '/buy-neo-hair-lotion-in-wholesale'
      preLoaderRoute: typeof BuyNeoHairLotionInWholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-science': {
      id: '/hair-science'
      path: '/hair-science'
      fullPath: '/hair-science'
      preLoaderRoute: typeof HairScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-spot-fake-vs-original-neo-hair-lotion': {
      id: '/how-to-spot-fake-vs-original-neo-hair-lotion'
      path: '/how-to-spot-fake-vs-original-neo-hair-lotion'
      fullPath: '/how-to-spot-fake-vs-original-neo-hair-lotion'
      preLoaderRoute: typeof HowToSpotFakeVsOriginalNeoHairLotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use-neo-hair-lotion': {
      id: '/how-to-use-neo-hair-lotion'
      path: '/how-to-use-neo-hair-lotion'
      fullPath: '/how-to-use-neo-hair-lotion'
      preLoaderRoute: typeof HowToUseNeoHairLotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-verify-original-neo-hair-lotion': {
      id: '/how-to-verify-original-neo-hair-lotion'
      path: '/how-to-verify-original-neo-hair-lotion'
      fullPath: '/how-to-verify-original-neo-hair-lotion'
      preLoaderRoute: typeof HowToVerifyOriginalNeoHairLotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neo-hair-lotion-reviews': {
      id: '/neo-hair-lotion-reviews'
      path: '/neo-hair-lotion-reviews'
      fullPath: '/neo-hair-lotion-reviews'
      preLoaderRoute: typeof NeoHairLotionReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-vs-fake': {
      id: '/real-vs-fake'
      path: '/real-vs-fake'
      fullPath: '/real-vs-fake'
      preLoaderRoute: typeof RealVsFakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/series': {
      id: '/blogs/series'
      path: '/blogs/series'
      fullPath: '/blogs/series'
      preLoaderRoute: typeof BlogsSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/$code': {
      id: '/combo/$code'
      path: '/combo/$code'
      fullPath: '/combo/$code'
      preLoaderRoute: typeof ComboCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison/neo-vs-minoxidil': {
      id: '/comparison/neo-vs-minoxidil'
      path: '/comparison/neo-vs-minoxidil'
      fullPath: '/comparison/neo-vs-minoxidil'
      preLoaderRoute: typeof ComparisonNeoVsMinoxidilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$slug': {
      id: '/ingredients/$slug'
      path: '/ingredients/$slug'
      fullPath: '/ingredients/$slug'
      preLoaderRoute: typeof IngredientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback/$intent': {
      id: '/payment/callback/$intent'
      path: '/payment/callback/$intent'
      fullPath: '/payment/callback/$intent'
      preLoaderRoute: typeof PaymentCallbackIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BuyNeoHairLotionInWholesaleRoute: BuyNeoHairLotionInWholesaleRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FaqRoute: FaqRoute,
  HairScienceRoute: HairScienceRoute,
  HowToSpotFakeVsOriginalNeoHairLotionRoute:
    HowToSpotFakeVsOriginalNeoHairLotionRoute,
  HowToUseRoute: HowToUseRoute,
  HowToUseNeoHairLotionRoute: HowToUseNeoHairLotionRoute,
  HowToVerifyOriginalNeoHairLotionRoute: HowToVerifyOriginalNeoHairLotionRoute,
  LegalRoute: LegalRoute,
  NeoHairLotionReviewsRoute: NeoHairLotionReviewsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PrivacyRoute: PrivacyRoute,
  RealVsFakeRoute: RealVsFakeRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrackOrderRoute: TrackOrderRoute,
  VerifyRoute: VerifyRoute,
  WholesaleRoute: WholesaleRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsSeriesRoute: BlogsSeriesRoute,
  ComboCodeRoute: ComboCodeRoute,
  ComparisonNeoVsMinoxidilRoute: ComparisonNeoVsMinoxidilRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  IngredientsSlugRoute: IngredientsSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  PaymentCallbackIntentRoute: PaymentCallbackIntentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
